sidebarPanel(
a(href="https://github.com/SurgicalInformatics/shinystats/blob/master/instructions/01_ttest.md",
  "Click for instructions", target="_blank"),
sliderInput("number",
            "Number of observations (sample size per group):",
            min = 5,
            max = 250,
            value = 20,
            step=5),
checkboxInput("jitter", h4("Show individual observations"), TRUE),
sliderInput("standard_deviation",
            "Variability (standard deviation):",
            min = 0.1,
            max = 2.0,
            value = 0.4,
            step=0.1),
sliderInput("effect_size",
            "Difference between the groups (effect size):",
            min = 0.1,
            max = 1.0,
            value = 0.2,
            step=0.05),
p("Mean body temperature of Justin Beaver: 37.2 degrees Celcius"),
textOutput("mean_otter"),
textOutput("mean_meerkat")
)